// Generated by Lintel conformance/sync-file-types.mjs. Do not edit.
export const fileTypeCatalog = {
    "$schema": "./schema/file-types-1.json",
    "version": 1,
    "revealLabels": {
        "win32": "Show in Explorer",
        "darwin": "Reveal in Finder",
        "linux": "Show in File Manager",
        "default": "Show in File Manager"
    },
    "types": [
        {
            "id": "csharp",
            "name": "C#",
            "extensions": [
                "cs"
            ],
            "filenames": [],
            "language": "csharp",
            "groups": [
                "sourceCode"
            ],
            "icon": "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI0OCIgaGVpZ2h0PSI0OCIgdmlld0JveD0iMCAwIDQ4IDQ4Ij48cmVjdCB4PSIxIiB5PSIxIiB3aWR0aD0iNDYiIGhlaWdodD0iNDYiIHJ4PSI4IiBmaWxsPSIjNjgyMTdhIi8+PHRleHQgeD0iMjQiIHk9IjMwIiB0ZXh0LWFuY2hvcj0ibWlkZGxlIiBmaWxsPSJ3aGl0ZSIgZm9udC1mYW1pbHk9InNhbnMtc2VyaWYiIGZvbnQtd2VpZ2h0PSJib2xkIiBmb250LXNpemU9IjE2Ij5DIzwvdGV4dD48L3N2Zz4K",
            "png": "icons/files/csharp.png",
            "badge": "C#",
            "color": "#68217a"
        },
        {
            "id": "typescript",
            "name": "TypeScript",
            "extensions": [
                "ts",
                "tsx",
                "mts",
                "cts"
            ],
            "filenames": [],
            "language": "typescript",
            "groups": [
                "sourceCode"
            ],
            "icon": "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI0OCIgaGVpZ2h0PSI0OCIgdmlld0JveD0iMCAwIDQ4IDQ4Ij48cmVjdCB4PSIxIiB5PSIxIiB3aWR0aD0iNDYiIGhlaWdodD0iNDYiIHJ4PSI4IiBmaWxsPSIjMzE3OGM2Ii8+PHRleHQgeD0iMjQiIHk9IjMwIiB0ZXh0LWFuY2hvcj0ibWlkZGxlIiBmaWxsPSJ3aGl0ZSIgZm9udC1mYW1pbHk9InNhbnMtc2VyaWYiIGZvbnQtd2VpZ2h0PSJib2xkIiBmb250LXNpemU9IjE2Ij5UUzwvdGV4dD48L3N2Zz4K",
            "png": "icons/files/typescript.png",
            "badge": "TS",
            "color": "#3178c6"
        },
        {
            "id": "javascript",
            "name": "JavaScript",
            "extensions": [
                "js",
                "jsx",
                "mjs",
                "cjs"
            ],
            "filenames": [],
            "language": "javascript",
            "groups": [
                "sourceCode"
            ],
            "icon": "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI0OCIgaGVpZ2h0PSI0OCIgdmlld0JveD0iMCAwIDQ4IDQ4Ij48cmVjdCB4PSIxIiB5PSIxIiB3aWR0aD0iNDYiIGhlaWdodD0iNDYiIHJ4PSI4IiBmaWxsPSIjODA2NTAwIi8+PHRleHQgeD0iMjQiIHk9IjMwIiB0ZXh0LWFuY2hvcj0ibWlkZGxlIiBmaWxsPSJ3aGl0ZSIgZm9udC1mYW1pbHk9InNhbnMtc2VyaWYiIGZvbnQtd2VpZ2h0PSJib2xkIiBmb250LXNpemU9IjE2Ij5KUzwvdGV4dD48L3N2Zz4K",
            "png": "icons/files/javascript.png",
            "badge": "JS",
            "color": "#806500"
        },
        {
            "id": "cpp",
            "name": "C++",
            "extensions": [
                "cpp",
                "cc",
                "cxx",
                "hpp",
                "hh",
                "hxx"
            ],
            "filenames": [],
            "language": "cpp",
            "groups": [
                "sourceCode"
            ],
            "icon": "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI0OCIgaGVpZ2h0PSI0OCIgdmlld0JveD0iMCAwIDQ4IDQ4Ij48cmVjdCB4PSIxIiB5PSIxIiB3aWR0aD0iNDYiIGhlaWdodD0iNDYiIHJ4PSI4IiBmaWxsPSIjMDA1OTljIi8+PHRleHQgeD0iMjQiIHk9IjMwIiB0ZXh0LWFuY2hvcj0ibWlkZGxlIiBmaWxsPSJ3aGl0ZSIgZm9udC1mYW1pbHk9InNhbnMtc2VyaWYiIGZvbnQtd2VpZ2h0PSJib2xkIiBmb250LXNpemU9IjE2Ij5DKys8L3RleHQ+PC9zdmc+Cg==",
            "png": "icons/files/cpp.png",
            "badge": "C++",
            "color": "#00599c"
        },
        {
            "id": "c",
            "name": "C",
            "extensions": [
                "c",
                "h"
            ],
            "filenames": [],
            "language": "c",
            "groups": [
                "sourceCode"
            ],
            "icon": "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI0OCIgaGVpZ2h0PSI0OCIgdmlld0JveD0iMCAwIDQ4IDQ4Ij48cmVjdCB4PSIxIiB5PSIxIiB3aWR0aD0iNDYiIGhlaWdodD0iNDYiIHJ4PSI4IiBmaWxsPSIjMzk0OWFiIi8+PHRleHQgeD0iMjQiIHk9IjMwIiB0ZXh0LWFuY2hvcj0ibWlkZGxlIiBmaWxsPSJ3aGl0ZSIgZm9udC1mYW1pbHk9InNhbnMtc2VyaWYiIGZvbnQtd2VpZ2h0PSJib2xkIiBmb250LXNpemU9IjE2Ij5DPC90ZXh0Pjwvc3ZnPgo=",
            "png": "icons/files/c.png",
            "badge": "C",
            "color": "#3949ab"
        },
        {
            "id": "python",
            "name": "Python",
            "extensions": [
                "py",
                "pyi",
                "pyw"
            ],
            "filenames": [],
            "language": "python",
            "groups": [
                "sourceCode"
            ],
            "icon": "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI0OCIgaGVpZ2h0PSI0OCIgdmlld0JveD0iMCAwIDQ4IDQ4Ij48cmVjdCB4PSIxIiB5PSIxIiB3aWR0aD0iNDYiIGhlaWdodD0iNDYiIHJ4PSI4IiBmaWxsPSIjMzc3NmFiIi8+PHRleHQgeD0iMjQiIHk9IjMwIiB0ZXh0LWFuY2hvcj0ibWlkZGxlIiBmaWxsPSJ3aGl0ZSIgZm9udC1mYW1pbHk9InNhbnMtc2VyaWYiIGZvbnQtd2VpZ2h0PSJib2xkIiBmb250LXNpemU9IjE2Ij5QWTwvdGV4dD48L3N2Zz4K",
            "png": "icons/files/python.png",
            "badge": "PY",
            "color": "#3776ab"
        },
        {
            "id": "rust",
            "name": "Rust",
            "extensions": [
                "rs"
            ],
            "filenames": [],
            "language": "rust",
            "groups": [
                "sourceCode"
            ],
            "icon": "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI0OCIgaGVpZ2h0PSI0OCIgdmlld0JveD0iMCAwIDQ4IDQ4Ij48cmVjdCB4PSIxIiB5PSIxIiB3aWR0aD0iNDYiIGhlaWdodD0iNDYiIHJ4PSI4IiBmaWxsPSIjOWI0MzE2Ii8+PHRleHQgeD0iMjQiIHk9IjMwIiB0ZXh0LWFuY2hvcj0ibWlkZGxlIiBmaWxsPSJ3aGl0ZSIgZm9udC1mYW1pbHk9InNhbnMtc2VyaWYiIGZvbnQtd2VpZ2h0PSJib2xkIiBmb250LXNpemU9IjE2Ij5SUzwvdGV4dD48L3N2Zz4K",
            "png": "icons/files/rust.png",
            "badge": "RS",
            "color": "#9b4316"
        },
        {
            "id": "go",
            "name": "Go",
            "extensions": [
                "go"
            ],
            "filenames": [],
            "language": "go",
            "groups": [
                "sourceCode"
            ],
            "icon": "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI0OCIgaGVpZ2h0PSI0OCIgdmlld0JveD0iMCAwIDQ4IDQ4Ij48cmVjdCB4PSIxIiB5PSIxIiB3aWR0aD0iNDYiIGhlaWdodD0iNDYiIHJ4PSI4IiBmaWxsPSIjMDA3ZDljIi8+PHRleHQgeD0iMjQiIHk9IjMwIiB0ZXh0LWFuY2hvcj0ibWlkZGxlIiBmaWxsPSJ3aGl0ZSIgZm9udC1mYW1pbHk9InNhbnMtc2VyaWYiIGZvbnQtd2VpZ2h0PSJib2xkIiBmb250LXNpemU9IjE2Ij5HTzwvdGV4dD48L3N2Zz4K",
            "png": "icons/files/go.png",
            "badge": "GO",
            "color": "#007d9c"
        },
        {
            "id": "java",
            "name": "Java",
            "extensions": [
                "java"
            ],
            "filenames": [],
            "language": "java",
            "groups": [
                "sourceCode"
            ],
            "icon": "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI0OCIgaGVpZ2h0PSI0OCIgdmlld0JveD0iMCAwIDQ4IDQ4Ij48cmVjdCB4PSIxIiB5PSIxIiB3aWR0aD0iNDYiIGhlaWdodD0iNDYiIHJ4PSI4IiBmaWxsPSIjYjQ0NDAwIi8+PHRleHQgeD0iMjQiIHk9IjMwIiB0ZXh0LWFuY2hvcj0ibWlkZGxlIiBmaWxsPSJ3aGl0ZSIgZm9udC1mYW1pbHk9InNhbnMtc2VyaWYiIGZvbnQtd2VpZ2h0PSJib2xkIiBmb250LXNpemU9IjE2Ij5KVjwvdGV4dD48L3N2Zz4K",
            "png": "icons/files/java.png",
            "badge": "JV",
            "color": "#b44400"
        },
        {
            "id": "ruby",
            "name": "Ruby",
            "extensions": [
                "rb",
                "rake"
            ],
            "filenames": [],
            "language": "ruby",
            "groups": [
                "sourceCode"
            ],
            "icon": "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI0OCIgaGVpZ2h0PSI0OCIgdmlld0JveD0iMCAwIDQ4IDQ4Ij48cmVjdCB4PSIxIiB5PSIxIiB3aWR0aD0iNDYiIGhlaWdodD0iNDYiIHJ4PSI4IiBmaWxsPSIjYTkxNDAxIi8+PHRleHQgeD0iMjQiIHk9IjMwIiB0ZXh0LWFuY2hvcj0ibWlkZGxlIiBmaWxsPSJ3aGl0ZSIgZm9udC1mYW1pbHk9InNhbnMtc2VyaWYiIGZvbnQtd2VpZ2h0PSJib2xkIiBmb250LXNpemU9IjE2Ij5SQjwvdGV4dD48L3N2Zz4K",
            "png": "icons/files/ruby.png",
            "badge": "RB",
            "color": "#a91401"
        },
        {
            "id": "powershell",
            "name": "PowerShell",
            "extensions": [
                "ps1",
                "psm1",
                "psd1"
            ],
            "filenames": [],
            "language": "powershell",
            "groups": [
                "sourceCode",
                "executable"
            ],
            "icon": "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI0OCIgaGVpZ2h0PSI0OCIgdmlld0JveD0iMCAwIDQ4IDQ4Ij48cmVjdCB4PSIxIiB5PSIxIiB3aWR0aD0iNDYiIGhlaWdodD0iNDYiIHJ4PSI4IiBmaWxsPSIjMDA2NmI4Ii8+PHRleHQgeD0iMjQiIHk9IjMwIiB0ZXh0LWFuY2hvcj0ibWlkZGxlIiBmaWxsPSJ3aGl0ZSIgZm9udC1mYW1pbHk9InNhbnMtc2VyaWYiIGZvbnQtd2VpZ2h0PSJib2xkIiBmb250LXNpemU9IjE2Ij5QUzwvdGV4dD48L3N2Zz4K",
            "png": "icons/files/powershell.png",
            "badge": "PS",
            "color": "#0066b8"
        },
        {
            "id": "shell",
            "name": "Shell",
            "extensions": [
                "sh",
                "bash",
                "zsh",
                "fish"
            ],
            "filenames": [],
            "language": "bash",
            "groups": [
                "sourceCode"
            ],
            "icon": "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI0OCIgaGVpZ2h0PSI0OCIgdmlld0JveD0iMCAwIDQ4IDQ4Ij48cmVjdCB4PSIxIiB5PSIxIiB3aWR0aD0iNDYiIGhlaWdodD0iNDYiIHJ4PSI4IiBmaWxsPSIjMzQ3YzJjIi8+PHRleHQgeD0iMjQiIHk9IjMwIiB0ZXh0LWFuY2hvcj0ibWlkZGxlIiBmaWxsPSJ3aGl0ZSIgZm9udC1mYW1pbHk9InNhbnMtc2VyaWYiIGZvbnQtd2VpZ2h0PSJib2xkIiBmb250LXNpemU9IjE2Ij5TSDwvdGV4dD48L3N2Zz4K",
            "png": "icons/files/shell.png",
            "badge": "SH",
            "color": "#347c2c"
        },
        {
            "id": "kotlin",
            "name": "Kotlin",
            "extensions": [
                "kt",
                "kts"
            ],
            "filenames": [],
            "language": "kotlin",
            "groups": [
                "sourceCode"
            ],
            "icon": "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI0OCIgaGVpZ2h0PSI0OCIgdmlld0JveD0iMCAwIDQ4IDQ4Ij48cmVjdCB4PSIxIiB5PSIxIiB3aWR0aD0iNDYiIGhlaWdodD0iNDYiIHJ4PSI4IiBmaWxsPSIjNzk1MmQ2Ii8+PHRleHQgeD0iMjQiIHk9IjMwIiB0ZXh0LWFuY2hvcj0ibWlkZGxlIiBmaWxsPSJ3aGl0ZSIgZm9udC1mYW1pbHk9InNhbnMtc2VyaWYiIGZvbnQtd2VpZ2h0PSJib2xkIiBmb250LXNpemU9IjE2Ij5LVDwvdGV4dD48L3N2Zz4K",
            "png": "icons/files/kotlin.png",
            "badge": "KT",
            "color": "#7952d6"
        },
        {
            "id": "swift",
            "name": "Swift",
            "extensions": [
                "swift"
            ],
            "filenames": [],
            "language": "swift",
            "groups": [
                "sourceCode"
            ],
            "icon": "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI0OCIgaGVpZ2h0PSI0OCIgdmlld0JveD0iMCAwIDQ4IDQ4Ij48cmVjdCB4PSIxIiB5PSIxIiB3aWR0aD0iNDYiIGhlaWdodD0iNDYiIHJ4PSI4IiBmaWxsPSIjYzY0ZTIyIi8+PHRleHQgeD0iMjQiIHk9IjMwIiB0ZXh0LWFuY2hvcj0ibWlkZGxlIiBmaWxsPSJ3aGl0ZSIgZm9udC1mYW1pbHk9InNhbnMtc2VyaWYiIGZvbnQtd2VpZ2h0PSJib2xkIiBmb250LXNpemU9IjE2Ij5TVzwvdGV4dD48L3N2Zz4K",
            "png": "icons/files/swift.png",
            "badge": "SW",
            "color": "#c64e22"
        },
        {
            "id": "php",
            "name": "PHP",
            "extensions": [
                "php"
            ],
            "filenames": [],
            "language": "php",
            "groups": [
                "sourceCode"
            ],
            "icon": "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI0OCIgaGVpZ2h0PSI0OCIgdmlld0JveD0iMCAwIDQ4IDQ4Ij48cmVjdCB4PSIxIiB5PSIxIiB3aWR0aD0iNDYiIGhlaWdodD0iNDYiIHJ4PSI4IiBmaWxsPSIjNjY1ODljIi8+PHRleHQgeD0iMjQiIHk9IjMwIiB0ZXh0LWFuY2hvcj0ibWlkZGxlIiBmaWxsPSJ3aGl0ZSIgZm9udC1mYW1pbHk9InNhbnMtc2VyaWYiIGZvbnQtd2VpZ2h0PSJib2xkIiBmb250LXNpemU9IjE2Ij5QSFA8L3RleHQ+PC9zdmc+Cg==",
            "png": "icons/files/php.png",
            "badge": "PHP",
            "color": "#66589c"
        },
        {
            "id": "sql",
            "name": "SQL",
            "extensions": [
                "sql"
            ],
            "filenames": [],
            "language": "sql",
            "groups": [
                "sourceCode"
            ],
            "icon": "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI0OCIgaGVpZ2h0PSI0OCIgdmlld0JveD0iMCAwIDQ4IDQ4Ij48cmVjdCB4PSIxIiB5PSIxIiB3aWR0aD0iNDYiIGhlaWdodD0iNDYiIHJ4PSI4IiBmaWxsPSIjMDA3NThmIi8+PHRleHQgeD0iMjQiIHk9IjMwIiB0ZXh0LWFuY2hvcj0ibWlkZGxlIiBmaWxsPSJ3aGl0ZSIgZm9udC1mYW1pbHk9InNhbnMtc2VyaWYiIGZvbnQtd2VpZ2h0PSJib2xkIiBmb250LXNpemU9IjE2Ij5TUUw8L3RleHQ+PC9zdmc+Cg==",
            "png": "icons/files/sql.png",
            "badge": "SQL",
            "color": "#00758f"
        },
        {
            "id": "css",
            "name": "CSS",
            "extensions": [
                "css",
                "scss",
                "sass",
                "less"
            ],
            "filenames": [],
            "language": "css",
            "groups": [
                "sourceCode"
            ],
            "icon": "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI0OCIgaGVpZ2h0PSI0OCIgdmlld0JveD0iMCAwIDQ4IDQ4Ij48cmVjdCB4PSIxIiB5PSIxIiB3aWR0aD0iNDYiIGhlaWdodD0iNDYiIHJ4PSI4IiBmaWxsPSIjMjQ1N2E3Ii8+PHRleHQgeD0iMjQiIHk9IjMwIiB0ZXh0LWFuY2hvcj0ibWlkZGxlIiBmaWxsPSJ3aGl0ZSIgZm9udC1mYW1pbHk9InNhbnMtc2VyaWYiIGZvbnQtd2VpZ2h0PSJib2xkIiBmb250LXNpemU9IjE2Ij5DU1M8L3RleHQ+PC9zdmc+Cg==",
            "png": "icons/files/css.png",
            "badge": "CSS",
            "color": "#2457a7"
        },
        {
            "id": "html",
            "name": "HTML",
            "extensions": [
                "html",
                "htm"
            ],
            "filenames": [],
            "language": "xml",
            "groups": [
                "sourceCode"
            ],
            "icon": "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI0OCIgaGVpZ2h0PSI0OCIgdmlld0JveD0iMCAwIDQ4IDQ4Ij48cmVjdCB4PSIxIiB5PSIxIiB3aWR0aD0iNDYiIGhlaWdodD0iNDYiIHJ4PSI4IiBmaWxsPSIjYmQ0MDFjIi8+PHRleHQgeD0iMjQiIHk9IjMwIiB0ZXh0LWFuY2hvcj0ibWlkZGxlIiBmaWxsPSJ3aGl0ZSIgZm9udC1mYW1pbHk9InNhbnMtc2VyaWYiIGZvbnQtd2VpZ2h0PSJib2xkIiBmb250LXNpemU9IjE2Ij5IVDwvdGV4dD48L3N2Zz4K",
            "png": "icons/files/html.png",
            "badge": "HT",
            "color": "#bd401c"
        },
        {
            "id": "markdown",
            "name": "Markdown",
            "extensions": [
                "md",
                "markdown",
                "mdown"
            ],
            "filenames": [],
            "language": "markdown",
            "groups": [
                "document"
            ],
            "icon": "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI0OCIgaGVpZ2h0PSI0OCIgdmlld0JveD0iMCAwIDQ4IDQ4Ij48cmVjdCB4PSIxIiB5PSIxIiB3aWR0aD0iNDYiIGhlaWdodD0iNDYiIHJ4PSI4IiBmaWxsPSIjNDA1MjcwIi8+PHRleHQgeD0iMjQiIHk9IjMwIiB0ZXh0LWFuY2hvcj0ibWlkZGxlIiBmaWxsPSJ3aGl0ZSIgZm9udC1mYW1pbHk9InNhbnMtc2VyaWYiIGZvbnQtd2VpZ2h0PSJib2xkIiBmb250LXNpemU9IjE2Ij5NRDwvdGV4dD48L3N2Zz4K",
            "png": "icons/files/markdown.png",
            "badge": "MD",
            "color": "#405270"
        },
        {
            "id": "text",
            "name": "Plain text",
            "extensions": [
                "txt",
                "log"
            ],
            "filenames": [],
            "language": "",
            "groups": [
                "document"
            ],
            "icon": "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI0OCIgaGVpZ2h0PSI0OCIgdmlld0JveD0iMCAwIDQ4IDQ4Ij48cmVjdCB4PSIxIiB5PSIxIiB3aWR0aD0iNDYiIGhlaWdodD0iNDYiIHJ4PSI4IiBmaWxsPSIjNTg2MTc0Ii8+PHRleHQgeD0iMjQiIHk9IjMwIiB0ZXh0LWFuY2hvcj0ibWlkZGxlIiBmaWxsPSJ3aGl0ZSIgZm9udC1mYW1pbHk9InNhbnMtc2VyaWYiIGZvbnQtd2VpZ2h0PSJib2xkIiBmb250LXNpemU9IjE2Ij5UWFQ8L3RleHQ+PC9zdmc+Cg==",
            "png": "icons/files/text.png",
            "badge": "TXT",
            "color": "#586174"
        },
        {
            "id": "json",
            "name": "JSON",
            "extensions": [
                "json",
                "jsonc"
            ],
            "filenames": [],
            "language": "json",
            "groups": [],
            "icon": "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI0OCIgaGVpZ2h0PSI0OCIgdmlld0JveD0iMCAwIDQ4IDQ4Ij48cmVjdCB4PSIxIiB5PSIxIiB3aWR0aD0iNDYiIGhlaWdodD0iNDYiIHJ4PSI4IiBmaWxsPSIjNTg2MTc0Ii8+PHRleHQgeD0iMjQiIHk9IjMwIiB0ZXh0LWFuY2hvcj0ibWlkZGxlIiBmaWxsPSJ3aGl0ZSIgZm9udC1mYW1pbHk9InNhbnMtc2VyaWYiIGZvbnQtd2VpZ2h0PSJib2xkIiBmb250LXNpemU9IjE2Ij57fTwvdGV4dD48L3N2Zz4K",
            "png": "icons/files/json.png",
            "badge": "{}",
            "color": "#586174"
        },
        {
            "id": "yaml",
            "name": "YAML",
            "extensions": [
                "yaml",
                "yml"
            ],
            "filenames": [],
            "language": "yaml",
            "groups": [],
            "icon": "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI0OCIgaGVpZ2h0PSI0OCIgdmlld0JveD0iMCAwIDQ4IDQ4Ij48cmVjdCB4PSIxIiB5PSIxIiB3aWR0aD0iNDYiIGhlaWdodD0iNDYiIHJ4PSI4IiBmaWxsPSIjNTg2MTc0Ii8+PHRleHQgeD0iMjQiIHk9IjMwIiB0ZXh0LWFuY2hvcj0ibWlkZGxlIiBmaWxsPSJ3aGl0ZSIgZm9udC1mYW1pbHk9InNhbnMtc2VyaWYiIGZvbnQtd2VpZ2h0PSJib2xkIiBmb250LXNpemU9IjE2Ij5ZTUw8L3RleHQ+PC9zdmc+Cg==",
            "png": "icons/files/yaml.png",
            "badge": "YML",
            "color": "#586174"
        },
        {
            "id": "toml",
            "name": "TOML",
            "extensions": [
                "toml"
            ],
            "filenames": [],
            "language": "toml",
            "groups": [],
            "icon": "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI0OCIgaGVpZ2h0PSI0OCIgdmlld0JveD0iMCAwIDQ4IDQ4Ij48cmVjdCB4PSIxIiB5PSIxIiB3aWR0aD0iNDYiIGhlaWdodD0iNDYiIHJ4PSI4IiBmaWxsPSIjNTg2MTc0Ii8+PHRleHQgeD0iMjQiIHk9IjMwIiB0ZXh0LWFuY2hvcj0ibWlkZGxlIiBmaWxsPSJ3aGl0ZSIgZm9udC1mYW1pbHk9InNhbnMtc2VyaWYiIGZvbnQtd2VpZ2h0PSJib2xkIiBmb250LXNpemU9IjE2Ij5UTUw8L3RleHQ+PC9zdmc+Cg==",
            "png": "icons/files/toml.png",
            "badge": "TML",
            "color": "#586174"
        },
        {
            "id": "ini",
            "name": "INI",
            "extensions": [
                "ini",
                "cfg",
                "conf"
            ],
            "filenames": [],
            "language": "ini",
            "groups": [],
            "icon": "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI0OCIgaGVpZ2h0PSI0OCIgdmlld0JveD0iMCAwIDQ4IDQ4Ij48cmVjdCB4PSIxIiB5PSIxIiB3aWR0aD0iNDYiIGhlaWdodD0iNDYiIHJ4PSI4IiBmaWxsPSIjNTg2MTc0Ii8+PHRleHQgeD0iMjQiIHk9IjMwIiB0ZXh0LWFuY2hvcj0ibWlkZGxlIiBmaWxsPSJ3aGl0ZSIgZm9udC1mYW1pbHk9InNhbnMtc2VyaWYiIGZvbnQtd2VpZ2h0PSJib2xkIiBmb250LXNpemU9IjE2Ij5JTkk8L3RleHQ+PC9zdmc+Cg==",
            "png": "icons/files/ini.png",
            "badge": "INI",
            "color": "#586174"
        },
        {
            "id": "xml",
            "name": "XML",
            "extensions": [
                "xml",
                "xaml",
                "csproj"
            ],
            "filenames": [],
            "language": "xml",
            "groups": [],
            "icon": "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI0OCIgaGVpZ2h0PSI0OCIgdmlld0JveD0iMCAwIDQ4IDQ4Ij48cmVjdCB4PSIxIiB5PSIxIiB3aWR0aD0iNDYiIGhlaWdodD0iNDYiIHJ4PSI4IiBmaWxsPSIjNTg2MTc0Ii8+PHRleHQgeD0iMjQiIHk9IjMwIiB0ZXh0LWFuY2hvcj0ibWlkZGxlIiBmaWxsPSJ3aGl0ZSIgZm9udC1mYW1pbHk9InNhbnMtc2VyaWYiIGZvbnQtd2VpZ2h0PSJib2xkIiBmb250LXNpemU9IjE2Ij5YTUw8L3RleHQ+PC9zdmc+Cg==",
            "png": "icons/files/xml.png",
            "badge": "XML",
            "color": "#586174"
        },
        {
            "id": "csv",
            "name": "CSV",
            "extensions": [
                "csv",
                "tsv"
            ],
            "filenames": [],
            "language": "",
            "groups": [],
            "icon": "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI0OCIgaGVpZ2h0PSI0OCIgdmlld0JveD0iMCAwIDQ4IDQ4Ij48cmVjdCB4PSIxIiB5PSIxIiB3aWR0aD0iNDYiIGhlaWdodD0iNDYiIHJ4PSI4IiBmaWxsPSIjNTg2MTc0Ii8+PHRleHQgeD0iMjQiIHk9IjMwIiB0ZXh0LWFuY2hvcj0ibWlkZGxlIiBmaWxsPSJ3aGl0ZSIgZm9udC1mYW1pbHk9InNhbnMtc2VyaWYiIGZvbnQtd2VpZ2h0PSJib2xkIiBmb250LXNpemU9IjE2Ij5DU1Y8L3RleHQ+PC9zdmc+Cg==",
            "png": "icons/files/csv.png",
            "badge": "CSV",
            "color": "#586174"
        },
        {
            "id": "image",
            "name": "Image",
            "extensions": [
                "png",
                "jpg",
                "jpeg",
                "gif",
                "bmp",
                "webp",
                "svg",
                "ico",
                "tif",
                "tiff"
            ],
            "filenames": [],
            "language": "",
            "groups": [
                "image",
                "media"
            ],
            "icon": "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI0OCIgaGVpZ2h0PSI0OCIgdmlld0JveD0iMCAwIDQ4IDQ4Ij48cmVjdCB4PSIxIiB5PSIxIiB3aWR0aD0iNDYiIGhlaWdodD0iNDYiIHJ4PSI4IiBmaWxsPSIjMjY3YjdjIi8+PHRleHQgeD0iMjQiIHk9IjMwIiB0ZXh0LWFuY2hvcj0ibWlkZGxlIiBmaWxsPSJ3aGl0ZSIgZm9udC1mYW1pbHk9InNhbnMtc2VyaWYiIGZvbnQtd2VpZ2h0PSJib2xkIiBmb250LXNpemU9IjE2Ij5JTUc8L3RleHQ+PC9zdmc+Cg==",
            "png": "icons/files/image.png",
            "badge": "IMG",
            "color": "#267b7c"
        },
        {
            "id": "video",
            "name": "Video",
            "extensions": [
                "mp4",
                "mkv",
                "webm",
                "mov",
                "avi"
            ],
            "filenames": [],
            "language": "",
            "groups": [
                "video",
                "media"
            ],
            "icon": "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI0OCIgaGVpZ2h0PSI0OCIgdmlld0JveD0iMCAwIDQ4IDQ4Ij48cmVjdCB4PSIxIiB5PSIxIiB3aWR0aD0iNDYiIGhlaWdodD0iNDYiIHJ4PSI4IiBmaWxsPSIjNzg1MmEzIi8+PHRleHQgeD0iMjQiIHk9IjMwIiB0ZXh0LWFuY2hvcj0ibWlkZGxlIiBmaWxsPSJ3aGl0ZSIgZm9udC1mYW1pbHk9InNhbnMtc2VyaWYiIGZvbnQtd2VpZ2h0PSJib2xkIiBmb250LXNpemU9IjE2Ij5WSUQ8L3RleHQ+PC9zdmc+Cg==",
            "png": "icons/files/video.png",
            "badge": "VID",
            "color": "#7852a3"
        },
        {
            "id": "audio",
            "name": "Audio",
            "extensions": [
                "mp3",
                "wav",
                "flac",
                "ogg",
                "m4a"
            ],
            "filenames": [],
            "language": "",
            "groups": [
                "audio",
                "media"
            ],
            "icon": "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI0OCIgaGVpZ2h0PSI0OCIgdmlld0JveD0iMCAwIDQ4IDQ4Ij48cmVjdCB4PSIxIiB5PSIxIiB3aWR0aD0iNDYiIGhlaWdodD0iNDYiIHJ4PSI4IiBmaWxsPSIjOTY3MDAwIi8+PHRleHQgeD0iMjQiIHk9IjMwIiB0ZXh0LWFuY2hvcj0ibWlkZGxlIiBmaWxsPSJ3aGl0ZSIgZm9udC1mYW1pbHk9InNhbnMtc2VyaWYiIGZvbnQtd2VpZ2h0PSJib2xkIiBmb250LXNpemU9IjE2Ij5BVUQ8L3RleHQ+PC9zdmc+Cg==",
            "png": "icons/files/audio.png",
            "badge": "AUD",
            "color": "#967000"
        },
        {
            "id": "pdf",
            "name": "PDF document",
            "extensions": [
                "pdf"
            ],
            "filenames": [],
            "language": "",
            "groups": [
                "document"
            ],
            "icon": "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI0OCIgaGVpZ2h0PSI0OCIgdmlld0JveD0iMCAwIDQ4IDQ4Ij48cmVjdCB4PSIxIiB5PSIxIiB3aWR0aD0iNDYiIGhlaWdodD0iNDYiIHJ4PSI4IiBmaWxsPSIjYjUyNjJiIi8+PHRleHQgeD0iMjQiIHk9IjMwIiB0ZXh0LWFuY2hvcj0ibWlkZGxlIiBmaWxsPSJ3aGl0ZSIgZm9udC1mYW1pbHk9InNhbnMtc2VyaWYiIGZvbnQtd2VpZ2h0PSJib2xkIiBmb250LXNpemU9IjE2Ij5QREY8L3RleHQ+PC9zdmc+Cg==",
            "png": "icons/files/pdf.png",
            "badge": "PDF",
            "color": "#b5262b"
        },
        {
            "id": "word",
            "name": "Word document",
            "extensions": [
                "docx",
                "doc"
            ],
            "filenames": [],
            "language": "",
            "groups": [
                "document"
            ],
            "icon": "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI0OCIgaGVpZ2h0PSI0OCIgdmlld0JveD0iMCAwIDQ4IDQ4Ij48cmVjdCB4PSIxIiB5PSIxIiB3aWR0aD0iNDYiIGhlaWdodD0iNDYiIHJ4PSI4IiBmaWxsPSIjMTg1YWJkIi8+PHRleHQgeD0iMjQiIHk9IjMwIiB0ZXh0LWFuY2hvcj0ibWlkZGxlIiBmaWxsPSJ3aGl0ZSIgZm9udC1mYW1pbHk9InNhbnMtc2VyaWYiIGZvbnQtd2VpZ2h0PSJib2xkIiBmb250LXNpemU9IjE2Ij5ET0M8L3RleHQ+PC9zdmc+Cg==",
            "png": "icons/files/word.png",
            "badge": "DOC",
            "color": "#185abd"
        },
        {
            "id": "excel",
            "name": "Excel workbook",
            "extensions": [
                "xlsx",
                "xls"
            ],
            "filenames": [],
            "language": "",
            "groups": [
                "document"
            ],
            "icon": "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI0OCIgaGVpZ2h0PSI0OCIgdmlld0JveD0iMCAwIDQ4IDQ4Ij48cmVjdCB4PSIxIiB5PSIxIiB3aWR0aD0iNDYiIGhlaWdodD0iNDYiIHJ4PSI4IiBmaWxsPSIjMTA3YzQxIi8+PHRleHQgeD0iMjQiIHk9IjMwIiB0ZXh0LWFuY2hvcj0ibWlkZGxlIiBmaWxsPSJ3aGl0ZSIgZm9udC1mYW1pbHk9InNhbnMtc2VyaWYiIGZvbnQtd2VpZ2h0PSJib2xkIiBmb250LXNpemU9IjE2Ij5YTFM8L3RleHQ+PC9zdmc+Cg==",
            "png": "icons/files/excel.png",
            "badge": "XLS",
            "color": "#107c41"
        },
        {
            "id": "powerpoint",
            "name": "PowerPoint presentation",
            "extensions": [
                "pptx",
                "ppt"
            ],
            "filenames": [],
            "language": "",
            "groups": [
                "document"
            ],
            "icon": "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI0OCIgaGVpZ2h0PSI0OCIgdmlld0JveD0iMCAwIDQ4IDQ4Ij48cmVjdCB4PSIxIiB5PSIxIiB3aWR0aD0iNDYiIGhlaWdodD0iNDYiIHJ4PSI4IiBmaWxsPSIjYzQzZTFjIi8+PHRleHQgeD0iMjQiIHk9IjMwIiB0ZXh0LWFuY2hvcj0ibWlkZGxlIiBmaWxsPSJ3aGl0ZSIgZm9udC1mYW1pbHk9InNhbnMtc2VyaWYiIGZvbnQtd2VpZ2h0PSJib2xkIiBmb250LXNpemU9IjE2Ij5QUFQ8L3RleHQ+PC9zdmc+Cg==",
            "png": "icons/files/powerpoint.png",
            "badge": "PPT",
            "color": "#c43e1c"
        },
        {
            "id": "archive",
            "name": "Archive",
            "extensions": [
                "zip",
                "7z",
                "rar",
                "tar",
                "gz",
                "bz2",
                "xz",
                "tgz"
            ],
            "filenames": [],
            "language": "",
            "groups": [
                "archive"
            ],
            "icon": "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI0OCIgaGVpZ2h0PSI0OCIgdmlld0JveD0iMCAwIDQ4IDQ4Ij48cmVjdCB4PSIxIiB5PSIxIiB3aWR0aD0iNDYiIGhlaWdodD0iNDYiIHJ4PSI4IiBmaWxsPSIjODY2MDE2Ii8+PHRleHQgeD0iMjQiIHk9IjMwIiB0ZXh0LWFuY2hvcj0ibWlkZGxlIiBmaWxsPSJ3aGl0ZSIgZm9udC1mYW1pbHk9InNhbnMtc2VyaWYiIGZvbnQtd2VpZ2h0PSJib2xkIiBmb250LXNpemU9IjE2Ij5aSVA8L3RleHQ+PC9zdmc+Cg==",
            "png": "icons/files/archive.png",
            "badge": "ZIP",
            "color": "#866016"
        },
        {
            "id": "executable",
            "name": "Executable",
            "extensions": [
                "exe",
                "msi",
                "bat",
                "cmd"
            ],
            "filenames": [],
            "language": "",
            "groups": [
                "executable"
            ],
            "icon": "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI0OCIgaGVpZ2h0PSI0OCIgdmlld0JveD0iMCAwIDQ4IDQ4Ij48cmVjdCB4PSIxIiB5PSIxIiB3aWR0aD0iNDYiIGhlaWdodD0iNDYiIHJ4PSI4IiBmaWxsPSIjNTg2MTc0Ii8+PHRleHQgeD0iMjQiIHk9IjMwIiB0ZXh0LWFuY2hvcj0ibWlkZGxlIiBmaWxsPSJ3aGl0ZSIgZm9udC1mYW1pbHk9InNhbnMtc2VyaWYiIGZvbnQtd2VpZ2h0PSJib2xkIiBmb250LXNpemU9IjE2Ij5FWEU8L3RleHQ+PC9zdmc+Cg==",
            "png": "icons/files/executable.png",
            "badge": "EXE",
            "color": "#586174"
        },
        {
            "id": "dockerfile",
            "name": "Dockerfile",
            "extensions": [],
            "filenames": [
                "Dockerfile",
                "Containerfile"
            ],
            "language": "dockerfile",
            "groups": [
                "sourceCode"
            ],
            "icon": "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI0OCIgaGVpZ2h0PSI0OCIgdmlld0JveD0iMCAwIDQ4IDQ4Ij48cmVjdCB4PSIxIiB5PSIxIiB3aWR0aD0iNDYiIGhlaWdodD0iNDYiIHJ4PSI4IiBmaWxsPSIjMTc2OWFhIi8+PHRleHQgeD0iMjQiIHk9IjMwIiB0ZXh0LWFuY2hvcj0ibWlkZGxlIiBmaWxsPSJ3aGl0ZSIgZm9udC1mYW1pbHk9InNhbnMtc2VyaWYiIGZvbnQtd2VpZ2h0PSJib2xkIiBmb250LXNpemU9IjE2Ij5ESzwvdGV4dD48L3N2Zz4K",
            "png": "icons/files/dockerfile.png",
            "badge": "DK",
            "color": "#1769aa"
        },
        {
            "id": "makefile",
            "name": "Makefile",
            "extensions": [],
            "filenames": [
                "Makefile",
                "GNUmakefile"
            ],
            "language": "makefile",
            "groups": [
                "sourceCode"
            ],
            "icon": "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI0OCIgaGVpZ2h0PSI0OCIgdmlld0JveD0iMCAwIDQ4IDQ4Ij48cmVjdCB4PSIxIiB5PSIxIiB3aWR0aD0iNDYiIGhlaWdodD0iNDYiIHJ4PSI4IiBmaWxsPSIjNTg2MTc0Ii8+PHRleHQgeD0iMjQiIHk9IjMwIiB0ZXh0LWFuY2hvcj0ibWlkZGxlIiBmaWxsPSJ3aGl0ZSIgZm9udC1mYW1pbHk9InNhbnMtc2VyaWYiIGZvbnQtd2VpZ2h0PSJib2xkIiBmb250LXNpemU9IjE2Ij5NSzwvdGV4dD48L3N2Zz4K",
            "png": "icons/files/makefile.png",
            "badge": "MK",
            "color": "#586174"
        },
        {
            "id": "file",
            "name": "File",
            "extensions": [],
            "filenames": [],
            "language": "",
            "groups": [],
            "icon": "data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHdpZHRoPSI0OCIgaGVpZ2h0PSI0OCIgdmlld0JveD0iMCAwIDQ4IDQ4Ij48cmVjdCB4PSIxIiB5PSIxIiB3aWR0aD0iNDYiIGhlaWdodD0iNDYiIHJ4PSI4IiBmaWxsPSIjNTg2MTc0Ii8+PHRleHQgeD0iMjQiIHk9IjMwIiB0ZXh0LWFuY2hvcj0ibWlkZGxlIiBmaWxsPSJ3aGl0ZSIgZm9udC1mYW1pbHk9InNhbnMtc2VyaWYiIGZvbnQtd2VpZ2h0PSJib2xkIiBmb250LXNpemU9IjEyIj5GSUxFPC90ZXh0Pjwvc3ZnPgo=",
            "png": "icons/files/file.png",
            "badge": "FILE",
            "color": "#586174"
        }
    ]
} as const
