<script lang="ts">import { base } from '$app/paths'; import Shot from '$lib/Shot.svelte';</script>
<svelte:head><title>Torbie · A terminal that explains its stalls</title><meta name="description" content="A desktop terminal for Windows, macOS and Linux. Tabby plugins keep loading. Recorded diagnostics explain stalls. Restored panes resume their commands." /></svelte:head>
<section class="hero wrap"><div><h1>The terminal that explains its stalls.</h1><p>A desktop terminal that keeps your Tabby plugins, records what blocked it, and brings your panes back running.</p><a class="button" href={`${base}/download/`}>Download Torbie <span aria-hidden="true">↗</span></a></div><Shot name="hero" alt="Torbie terminal showing public Git history and the Torbie repository URL" eager /></section>
<div class="wrap home-body">
<section class="split"><h2>Your plugins keep loading.</h2><div><p>Torbie derives from Tabby and keeps its plugin API. Package names, module imports and the plugin keyword stay in place.</p><p>Three third-party plugins were loaded in a scratch profile. Their dependencies resolved and their configuration providers ran.</p><a href={`${base}/features/torbie/`}>Read the compatibility evidence</a></div></section>
<section class="incident"><h2>It says why it froze.</h2><p>A long stall leaves a record. Torbie attributes synchronous work in the main process and every renderer.</p><blockquote><pre>renderer event loop blocked 71.3s during "ready" — 98% synchronous I/O: fs.readFileSync ×58214 (41.0s), fs.unlinkSync ×58214 (28.2s)</pre></blockquote><div class="call-breakdown"><div><code>fs.readFileSync</code><strong>41.0s</strong><span>58,214 calls</span></div><div><code>fs.unlinkSync</code><strong>28.2s</strong><span>58,214 calls</span></div></div><a href={`${base}/features/diagnostics-log/`}>Inspect the recorded diagnostics</a></section>
<section class="split"><h2>A pane comes back running.</h2><div><p>Torbie asks each pane what it is running and saves that with the layout. After a restart, it types the command into the restored shell.</p><p>Detection has limits. The feature page records which commands and session types are covered.</p><a href={`${base}/features/session-resume/`}>See how pane recovery works</a></div></section>
<section class="split media-section"><div class="preview-evidence"><code>https://github.com/aylith-labs/torbie</code><p>A public URL is the starting point. The integration supplies the summary and the preview opens beside the terminal.</p><a href="https://github.com/aylith-labs/torbie/tree/main/tabby-links">Read the integration source</a></div><div><h2>Read the link beside the work.</h2><p>Hover over a terminal link for a summary. Open its preview in a pane beside the terminal. Declarative integration rules decide what is fetched and shown.</p><a href={`${base}/features/preview-pane/`}>Explore link previews</a></div></section>
<section class="split media-section"><div><h2>Every build. A reason when it fails.</h2><p>The Builds page inventories installations, running processes and source checkouts. The doctor checks a build and names the cause when it cannot start.</p><a href={`${base}/features/builds-doctor/`}>Read what the doctor checks</a></div><div class="build-evidence"><h3>What the doctor looks for</h3><ul><li>Missing builtin plugins</li><li>Build and plugin provenance</li><li>Processes that never finish starting</li></ul><a href={`${base}/features/builds-page/`}>Explore the build inventory</a></div></section>
<section class="limits"><h2>Known limits.</h2><p>Torbie is an Electron app. If memory use is your first priority, consider Alacritty or WezTerm.</p><dl><div><dt>Emoji width is wrong.</dt><dd>Some emoji occupy the wrong number of terminal cells.</dd></div><div><dt>Stale glyphs remain unexplained.</dt><dd>The test built to look for the artifacts has not reproduced them.</dd></div><div><dt>macOS is checked in source.</dt><dd>The icons and workflows were reviewed file by file. They have never been seen on a Mac.</dd></div><div><dt>Builds are unsigned.</dt><dd>Windows SmartScreen warns. macOS requires “Open anyway”. The download page explains this beside the files.</dd></div></dl></section>
<section class="closing"><h2>Keep the session.<br />Keep the evidence.</h2><a class="button" href={`${base}/download/`}>Download Torbie <span aria-hidden="true">↗</span></a><a href={`${base}/features/`}>Browse every feature</a></section>
</div>
