<script lang="ts">
 import { onMount } from 'svelte'; import SelectMenu from '$lib/SelectMenu.svelte'; let { data } = $props(); let platform = $state(''); let arch = $state('');
 const available = $derived(data.release.assets.filter(a => (!platform || a.platform === platform) && (!arch || a.arch === arch)));
 const primary = $derived(available.find(a => a.format === (platform === 'Windows' ? 'exe' : platform === 'macOS' ? 'dmg' : 'AppImage')));
 onMount(async () => { const ua = navigator.userAgent; platform = /Windows/.test(ua) ? 'Windows' : /Macintosh|Mac OS X/.test(ua) && !/iPhone|iPad/.test(ua) ? 'macOS' : /Linux/.test(ua) && !/Android/.test(ua) ? 'Linux' : ''; const hints = (navigator as Navigator & { userAgentData?: { getHighEntropyValues: (keys: string[]) => Promise<{ architecture?: string; bitness?: string }> } }).userAgentData; try { const h = await hints?.getHighEntropyValues(['architecture','bitness']); if (h?.architecture === 'arm') arch = h.bitness === '64' ? 'arm64' : 'armv7l'; else if (h?.architecture === 'x86' && h.bitness === '64') arch = 'x64'; else if (/aarch64|arm64/i.test(ua)) arch = 'arm64'; else if (/Win64|x86_64/.test(ua)) arch = 'x64'; } catch {} });
</script>
<svelte:head><title>Download Torbie</title><meta name="description" content="Download Torbie for Windows, macOS and Linux. Installers, portable builds, architecture choices and unsigned-build guidance." /></svelte:head>
<div class="wrap download"><h1>Download Torbie.</h1><p>{data.release.version ? `${data.release.version}. ` : ''}Windows, macOS and Linux. Choose an installer or a portable build.</p>
<section class="download-choice" aria-label="Choose your download"><div class="filters"><SelectMenu label="Operating system" value={platform} options={[{value:'',label:'Choose your platform',disabled:!!platform},...['Windows','macOS','Linux'].map(value=>({value,label:value}))]} onchange={value=>{platform=value;arch=''}} /><SelectMenu label="Architecture" value={arch} options={[{value:'',label:'Choose architecture',disabled:!!arch},{value:'x64',label:'x64 / Intel'},{value:'arm64',label:'ARM64 / Apple silicon'},...(platform==='Linux'?[{value:'armv7l',label:'ARMv7'}]:[])]} onchange={value=>arch=value} /></div>
{#if platform && arch && primary}<a class="button" href={primary.browser_download_url}>Download for {platform} {arch} <span class="format">{primary.format}</span></a>{:else}<a class="button" href={data.release.available ? '#all-downloads' : data.release.url}>{data.release.available ? 'Choose from all downloads' : 'Open GitHub releases'}</a><p class="small">{data.release.available ? 'Confirm your architecture if your browser cannot identify it.' : 'The release API could not be reached during this build. GitHub lists the current files.'}</p>{/if}
<div class="install-note"><h2>Before you install</h2><p>These builds are unsigned. Windows SmartScreen warns; verify the source before choosing “More info” and “Run anyway”. On macOS, use “Open anyway” in Privacy &amp; Security.</p><p>Torbie has its own app ID, install directory and configuration directory. On first launch it copies your Tabby profile forward. The original profile stays where it is. Windows installs alongside Tabby. Linux deb and rpm packages declare that they replace tabby-terminal; choose an AppImage or archive to keep the installed package.</p></div></section>
<section id="all-downloads"><h2>All downloads</h2>{#each ['Windows','macOS','Linux'] as os}<section class="platform"><h3>{os}</h3><p class="small">{os === 'Windows' ? 'Unsigned installer or portable ZIP. SmartScreen warns.' : os === 'macOS' ? 'Unsigned disk image or ZIP. Use “Open anyway”.' : 'The deb and rpm replace the Tabby package. Use AppImage or an archive to keep it.'}</p><div class="asset-list">{#each data.release.assets.filter(a => a.platform === os) as asset}<a href={asset.browser_download_url}><span>{asset.arch} <strong>{asset.format === 'exe' ? 'Installer' : asset.format === 'zip' ? 'Portable ZIP' : asset.format}</strong></span><span>{Math.round(asset.size / 1048576)} MB <span aria-hidden="true">↗</span></span></a>{/each}</div></section>{/each}{#if !data.release.available}<a href={data.release.url}>See current release files on GitHub</a>{/if}</section><p><a href={data.release.url}>Release notes and checksums on GitHub</a></p></div>
