<script lang="ts">import { base } from '$app/paths'; let { data } = $props(); const f = $derived(data.feature); const d = $derived(data.detail);</script>
<svelte:head><title>{f.title} · Torbie</title><meta name="description" content={f.desc} /></svelte:head>
<article class="wrap detail"><a href={`${base}/features/`}>All features</a><h1>{f.title}</h1><p class="lead">{f.desc}</p><div class="diffstat"><span>{f.catLabel}</span><span>Added {f.dateAdded}</span><span>{f.files} {f.files === 1 ? 'file' : 'files'}</span><span>+{f.ins.toLocaleString('en')} / −{f.del.toLocaleString('en')} lines</span></div>
{#if d.problem}<details class="feature-disclosure" data-guide-title={f.title} data-guide={f.desc}><summary>The problem<span aria-hidden="true">+</span></summary><div><p>{@html d.problem}</p></div></details>{/if}
{#if d.how}<details class="feature-disclosure" data-guide-title={f.title} data-guide={f.desc}><summary>How it works<span aria-hidden="true">+</span></summary><div><p>{@html d.how}</p></div></details>{/if}
{#if d.steps?.length}<details class="feature-disclosure" data-guide-title={f.title} data-guide={f.desc}><summary>Try it<span aria-hidden="true">+</span></summary><div><ol>{#each d.steps as step}<li>{@html step}</li>{/each}</ol></div></details>{/if}
{#if d.settings?.length}<details class="feature-disclosure" data-guide-title={f.title} data-guide={f.desc}><summary>Settings<span aria-hidden="true">+</span></summary><div><ul>{#each d.settings as setting}<li><code>{setting.key}</code>: <code>{setting.def}</code>{#if setting.note}<p>{@html setting.note}</p>{/if}</li>{/each}</ul></div></details>{/if}
{#if d.sample}<details class="feature-disclosure" data-guide-title={f.title} data-guide={f.desc}><summary>{d.sample.label}<span aria-hidden="true">+</span></summary><div><pre>{d.sample.text}</pre></div></details>{/if}
{#if d.notes?.length}<details class="feature-disclosure" data-guide-title={f.title} data-guide={f.desc}><summary>Details<span aria-hidden="true">+</span></summary><div><ul>{#each d.notes as note}<li>{@html note}</li>{/each}</ul></div></details>{/if}
<details class="feature-disclosure" data-guide-title={f.title} data-guide={f.desc}><summary>What this does not claim<span aria-hidden="true">+</span></summary><div><ul>{#each d.caveats || [] as caveat}<li>{@html caveat}</li>{:else}<li>The source catalogue records no separate caveats for this entry. The implementation and evidence above define its scope.</li>{/each}</ul></div></details>
{#if d.upstream}<details class="feature-disclosure" data-guide-title={f.title} data-guide={f.desc}><summary>In upstream Tabby<span aria-hidden="true">+</span></summary><div><p>{@html d.upstream}</p></div></details>{/if}
<details class="feature-disclosure" data-guide-title={f.title} data-guide={f.desc}><summary>Source commits<span aria-hidden="true">+</span></summary><div><div class="commits">{#each f.commits as sha}<a href={`https://github.com/aylith-labs/torbie/commit/${sha}`}><code>{sha}</code></a>{/each}</div></div></details></article>
