export const demos = [
 {id:'claude',name:'Claude Code',icon:'fas fa-robot'},
 {id:'codex',name:'Codex',icon:'fas fa-code'},
 {id:'shefrd',name:'Shefrd',icon:'fas fa-columns'},
 {id:'polygit',name:'Polygit',icon:'fab fa-git-alt'},
 {id:'neovim',name:'Neovim',icon:'fas fa-file-code'},
 {id:'btop',name:'btop',icon:'fas fa-chart-bar'},
 {id:'logs',name:'Vite dev server',icon:'fas fa-stream'},
 {id:'tests',name:'Playwright',icon:'fas fa-check'},
];
const copper='\x1b[38;2;201;122;58m',green='\x1b[32m',blue='\x1b[34m',muted='\x1b[39m',reset='\x1b[0m';
export function screen(id:string,choice=0):string{
 const title=demos.find(d=>d.id===id)?.name || 'Shell';
 const header=`${copper}${title}${reset}  ${muted}· interactive demo${reset}\r\n${muted}/workspace/studio${reset}\r\n\r\n`;
 const content:Record<string,string[]>={
 claude:[`${copper}❯${reset} Arrange a workspace and check the changes.`, '', '● I’ll open a test pane beside the application.', '', `${muted}MCP · list_tabs${reset}`, '  agent · application', '', `${muted}MCP · split_tab${reset}`, '  A new test pane, alongside the current session.', '', `${muted}MCP · exec_command${reset}`, '  npm test', `${green}  ✓ All checks passed${reset}`, '', '● The result is in the test pane. Ready to review.', '', `${copper}❯${reset} Try a demo command: help, test, clear, shefrd`],
 codex:[`${blue}Codex${reset} · workspace review`, '', '› Review the keyboard navigation changes.', '', '• Read src/keyboard.ts', '• Read tests/keyboard.test.ts', '', '• Ran npm test', `${green}  ✓ Tab moves between controls`, '  ✓ Escape returns focus', `  ✓ Arrow keys move through options${reset}`, '', '• No regressions found in this demo run.', '', '› Type help to explore the demo'],
 shefrd:[`${copper}SHEFRD${reset}                        studio / feature/workspace`, '', '  spaces               agents', '', ...['Claude · implement layout · working','Codex · review changes · waiting','tests · npm test · done'].map((s,i)=>`${i===choice%3?green+'❯':' '} ${s}${reset}`), '', `${muted}────────────────────────────────────────────${reset}`, '', choice%3===0?'● Updating the terminal workspace.':choice%3===1?'› Review complete. Waiting for the next task.':'✓ 18 tests passed. No failed checks.', '', '  Each agent keeps its own terminal session.', '', `${muted}↑/↓ select an agent · Enter inspect · q return${reset}`],
 polygit:[`${green}[1] polygit · ~/projects · 3 repos${reset}`, '', '  Repository          Branch       Status', ...['torbie              main         updated','shefrd              main         up-to-date','polygit             main         updated'].map((s,i)=>`${i===choice%3?green+'❯':' '} ${s}${reset}`), '', `${muted}────────────────────────────────────────────${reset}`, `${green}[2] Command log · ${['torbie','shefrd','polygit'][choice%3]}${reset}`, '', '$ git pull --ff-only', choice%3===1?'Already up to date.':'Updating 2 commits · fast-forward', '', '  Result: 3 repositories checked · 0 errors', '', `${muted}j/k select repo · Space result summary · q return${reset}`],
 neovim:[`${blue}src/workspace.ts${reset}`, '', `${muted} 1${reset}  export function workspace() {`, `${muted} 2${reset}    return {`, `${muted} 3${reset}      name: 'studio',`, `${muted} 4${reset}      panes: ['agent', 'application', 'tests'],`, `${muted} 5${reset}      restore: true,`, `${muted} 6${reset}    }`, `${muted} 7${reset}  }`, '', '~', '~', '', `${blue} NORMAL ${reset} workspace.ts                 1:1`, `${muted}i insert a demo note · Esc normal · :q return${reset}`],
 btop:[`${green}┌─ cpu ──────────────────────────────────┐`, '│  ▁▂▁▃▆▅▂▃▁▁▃▅▆▅▂▁    CPU  38%        │', `└───────────────────────────────────────┘${reset}`, `${blue}┌─ mem ──────────┐ ┌─ proc ───────────────┐`, '│ 4.8 / 16 GB    │ │ PID   program  CPU  │', '│ ▰▰▰▱▱▱▱▱ 30%  │ │ 401   claude   12%  │', '│               │ │ 402   codex     8%  │', '│ disk  39%      │ │ 403   shefrd    1%  │', `└───────────────┘ └─────────────────────┘${reset}`, `${green}┌─ net ──────────────────────────────────┐`, '│ ↓ 18 KiB/s    ▁▁▂▃▁▅▂▃▁    ↑ 2 KiB/s │', `└───────────────────────────────────────┘${reset}`, '', `${muted}Seeded process data · q return${reset}`],
 logs:[`${copper}❯${reset} npm run dev`, '', `${green}  VITE v8.3.0${reset}  ready in 184 ms`, '', '  ➜  Local:   http://localhost:5173/', '', `${muted}10:42:03${reset} [vite] page reload src/workspace.ts`, `${muted}10:42:05${reset} [vite] hmr update /src/App.svelte`, `${green}  ✓ Workspace changes are ready to preview${reset}`, '', '  The agent can keep this server beside its test pane.', '', `${muted}Seeded dev server output · type test to run checks${reset}`],
 tests:[`${copper}❯${reset} npx playwright test`, '', '  Running 18 tests using 3 workers', `${green}    ✓ opens an agent session`, '    ✓ [chromium] adds a test pane', `    ✓ restores the layout${reset}`, '', '  keyboard', `${green}    ✓ Tab advances focus`, '    ✓ [webkit] Escape closes the menu', `    ✓ arrows select an option${reset}`, '', `${green}  18 passed · 0 failed${reset}`, `${muted}  Demo output; no commands run on your computer.${reset}`, '', '❯ Type test to run again'],
 };
 return '\x1b[2J\x1b[H'+header+(content[id]||['❯ Type help']).join('\r\n')+'\r\n';
}
